# Generated by Django 4.0.3 on 2022-03-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tansaction_id',
            new_name='transaction_id',
        ),
    ]
